export const ADD_USER = "ADD_USER";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";


export const FETCH_QUIZ_CATEGORIES_REQUEST = "FETCH_QUIZ_CATEGORIES_REQUEST";
export const FETCH_QUIZ_CATEGORIES_SUCCESS = "FETCH_QUIZ_CATEGORIES_SUCCESS";
export const FETCH_QUIZ_CATEGORIES_FAILURE = "FETCH_QUIZ_CATEGORIES_FAILURE";

export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE";